[package]
name = "natsio"
version = "0.3.2"
description = "A Rust NATS client"
authors = ["Derek Collison <derek@nats.io>", "Tyler Neely <tyler@nats.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/nats-io/nats.rs"
repository = "https://github.com/nats-io/nats.rs"
readme = "README.md"
keywords = ["nats", "client", "messaging", "api"]
categories = ["network-programming", "api-bindings"]

[lib]
name = "nats"

[badges]
travis-ci = { repository = "nats-io/nats.rs", branch = "master" }
maintenance = { status = "actively-developed" }

[profile.dev]
panic = 'abort'

[dependencies]
serde = { version = "1.0.106", features = ["derive"] }
serde_json = "1.0.51"
regex = "1.3.7"
nuid = "0.2.1"
lazy_static = "1.4.0"
nom = "5.1.1"
crossbeam-channel = "0.4.2"
parking_lot = "0.10.2"
rand = "0.7.3"
native-tls = "0.2.4"
log = "0.4.8"
nkeys = "0.0.9"
base64-url = "1.1.13"

[dev-dependencies]
criterion = "0.3.1"
quicli = "0.4.0"
structopt = "0.3.14"

[[bench]]
name = "nats_bench"
harness = false

[[example]]
name = "nats-box"
path = "examples/nats-box/main.rs"

[[example]]
name = "serde-json"
path = "examples/serde-json/main.rs"
